[package]
name = "sorbonne-presentation"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["David Hajage"]
license = "MIT"
description = "A structured presentation theme for Sorbonne University, based on presentate and navigator."
compiler = "0.12.0"
categories = ["presentation"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
